port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: INDO 1
    type: trojan
    server: 104.18.2.2
    port: 443
    type: vmess
    password: a1c93ee4-84c9-42c9-b7ed-f86c65b72f67
    udp: true
    sni: samudra.basecampsedekahbumi.my.id
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /trojan-ws
      headers:
        Host: samudra.basecampsedekahbumi.my.id
  - name: INDO 2
    type: trojan
    server: 104.18.2.2
    port: 443
    password: a1c93ee4-84c9-42c9-b7ed-f86c65b72f67
    udp: true
    sni: samudra.basecampsedekahbumi.my.id
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /trojan-ws
      headers:
        Host: samudra.basecampsedekahbumi.my.id
  - name: INDO 3
    type: trojan
    server: 104.18.2.2
    port: 443
    password: a1c93ee4-84c9-42c9-b7ed-f86c65b72f67
    udp: true
    sni: samudra.basecampsedekahbumi.my.id
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /trojan-ws
      headers:
        Host: samudra.basecampsedekahbumi.my.id

proxy-groups:
  - name: AKUN
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - INDO 1
      - INDO 2
      - INDO 3

  - name: GAME
    type: select
    proxies:
     - AKUN
     - DIRECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,AKUN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,AKUN
 - RULE-SET,indo,AKUN
 - RULE-SET,Sosmed,AKUN
 - RULE-SET,Streaming,AKUN
 - RULE-SET,Tiktok,AKUN
 - RULE-SET,Meta,AKUN
 - RULE-SET,PortGame,GAME
 - MATCH,AKUN


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  
